apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-nginx
  namespace: default
subjects:
- kind: User
  name: user-nginx
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-nginx
  apiGroup: rbac.authorization.k8s.io
