---
# tasks file for vector
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- include_tasks:
    file: "{{ lookup('first_found', params) }}"
    apply:
      tags: vector
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr }}.yml"
        - 'empty.yml'
  tags: vector

- include_tasks:
    file: configure.yml
    apply:
      tags: vector
  tags: vector
