- name: Version OS
  gather_facts: false
  hosts: all
  become: yes

  pre_tasks:
    - name: Validating the ssh port is open and
      wait_for:
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        port: 22
        delay: 5
        timeout: 300
        state: started
        search_regex: OpenSSH

  tasks:
  - name: Show version OS
    debug:
      msg: "{{ lookup('ansible.builtin.file', '/etc/os-release')\
           | regex_search('VERSION=(.*)', '\\1') | first | replace('\"','') }}"
