apiVersion: apps/v1
kind: Deployment
metadata:
  name: busypod
  namespace: default
  labels:
    app: busypod
spec:
  selector:
    matchLabels:
      app: busypod
  replicas: 1
  template:
    metadata:
      labels:
        app: busypod
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
          command:
            - "sh"
            - "-c"
            - "num=1; while true; do echo String number $num >> /mnt/share-dir/file.txt; num=$((num+1)); sleep 5; done"
          volumeMounts:
            - name: share-dir
              mountPath: /mnt/share-dir
        - name: multitool
          image: wbitt/network-multitool
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
          ports:
            - name: multitool-http
              containerPort: 80
            - name: multitool-https
              containerPort: 443
          volumeMounts:
            - name: share-dir
              mountPath: /mnt/share-dir
      volumes:
        - name: share-dir
          persistentVolumeClaim:
            claimName: pvc-busypod
