apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-monitor-log
  namespace: default
  labels:
    type: nfs
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
