apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-busypod
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
