---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos_8
    image: docker.io/library/centos:8
    pre_build_image: false
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
verifier:
  name: ansible
