---
# tasks file for lighthouse
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- include_tasks:
    file: "{{ lookup('first_found', params) }}"
    apply:
      tags: lighthouse
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr }}.yml"
        - 'empty.yml'
  tags: lighthouse
