apiVersion: v1
kind: Service
metadata:
  name: http-application-clusterip
  namespace: default
  labels:
    app: http-application
spec:
  type: ClusterIP
  selector:
    app: http-application
  ports:
    - name: http-nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: http-multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
