apiVersion: v1
kind: Service
metadata:
  name: http-application-nodeport
  namespace: default
  labels:
    app: http-application
spec:
  type: NodePort
  selector:
    app: http-application
  ports:
    - name: http-nginx
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
