apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-{{ .Values.versionApp }}
  namespace: {{  .Values.namespace }}
  labels:
    app: http-application
spec:
  selector:
    matchLabels:
      app: http-application-app-{{ .Values.versionApp }}
  replicas: 1
  template:
    metadata:
      labels:
        app: http-application-app-{{ .Values.versionApp }}
    spec:
      volumes:
        - name: vol-nginx
          configMap:
            name: configmap-app-{{ .Values.versionApp }}
      containers:
        - name: nginx
          image: nginx:{{ .Values.versionImage }}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
              cpu: "{{ .Values.resources.cpu }}"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: vol-nginx
              mountPath: /usr/share/nginx/html
