apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate-app{{ .Values.versionApp }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secret.tls.crt }}
  tls.key: {{ .Values.secret.tls.key }}