apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-application
  namespace: default
  labels:
    app: http-application
spec:
  selector:
    matchLabels:
      app: http-application
  replicas: 1
  template:
    metadata:
      labels:
        app: http-application
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
      initContainers:
        - name: init-nginx
          image: busybox:latest
          command: ['sh', '-c', "until nslookup http-application.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
