apiVersion: v1
kind: Service
metadata:
  name: http-application
  namespace: default
spec:
  selector:
    app: http-application
  ports:
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-multitool
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https-multitool
      protocol: TCP
      port: 8083
      targetPort: 8083
