#cloud-config
datasource:
  Ec2:
    strict_id: false

ssh_pwauth: no

users:
  - name: ${ssh_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
       - ${ssh_key}

package_update: true
package_upgrade: true
                
packages:
  - nano
  - python3-pip
