version: '3.8'

services:
  grafana:
    image: grafana/grafana
    networks:
      mnt_stack:
        ipv4_address: 172.20.0.5
    ports:
      - '3000:3000'
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus:/etc/prometheus/'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      mnt_stack:
        ipv4_address: 172.20.0.10
    ports:
      - '9090:9090'
    restart: always
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    networks:
      mnt_stack:
        ipv4_address: 172.20.0.15
    ports:
      - '9100:9100'
    restart: always

networks:
  mnt_stack:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
