{
 "title": "node-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory, B",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"${instance}\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "FS Size, B",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"${instance}\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Utilization, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{instance=\"${instance}\", mode=\"idle\"}[30s])) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU LA %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{instance=\"${instance}\", mode!=\"idle\"}[1m])) without (mode)) * 100",
     "legendFormat": "1m"
    },
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{instance=\"${instance}\", mode!=\"idle\"}[5m])) without (mode)) * 100",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{instance=\"${instance}\", mode!=\"idle\"}[15m])) without (mode)) * 100",
     "legendFormat": "15m"
    }
   ]
  }
 ]
}