apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.name }}-deployment
  namespace: {{  .Values.namespace }}
  labels:
    app: {{  .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{  .Values.name }}
  replicas: {{  .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{  .Values.name }}
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:{{  .Values.versionImage }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PMA_HOST
              value: "{{  .Values.db.host }}"
            - name: PMA_PORT
              value: "{{  .Values.db.port }}"
