apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.name }}-service
  namespace: {{  .Values.namespace }}
  labels:
    app: {{  .Values.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{  .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{  .Values.loadBalancerPort }}
      targetPort: 80
