apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor-log
  namespace: default
  labels:
    app: monitor-log
spec:
  selector:
    matchLabels:
      app: monitor-log
  template:
    metadata:
      labels:
        app: monitor-log
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
          ports:
            - name: multitool-http
              containerPort: 80
            - name: multitool-https
              containerPort: 443
          volumeMounts:
            - name: syslog
              mountPath: /mnt/log/syslog
      volumes:
        - name: syslog
          hostPath:
            path: /var/log/syslog
