- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://apt.vector.dev/pool/v/ve/\
         vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
    mode: "0644"
    validate_certs: false

- name: Install vector package
  become: "{{ true if 'sudo' in ansible_facts.packages else false }}"
  ansible.builtin.apt:
    deb: /tmp/vector_{{ vector_version }}-1_amd64.deb
